version: '3.7'

services:
  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/home/myuser/app
    ports:
      - 8000:8000
    # command: sh -c "pip install -r requirements.txt && python manage.py runserver"
