version: '3.9'

services:
  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/home/go/app
    ports:
      - 8000:8000
    command: sh -c "go run learn-go/server.go"
