version: '3.9'

services:
  go:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./:/home/go/app
    ports:
      - 8080:8080
    command: sh -c "tail -f /dev/null"
