# Build state
FROM --platform=linux/amd64 public.ecr.aws/docker/library/golang:1.21.4-alpine3.18 AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /main main.go

# Deploy state
FROM --platform=linux/amd64 public.ecr.aws/docker/library/alpine:3.18

RUN addgroup -g 1000 app \
    && adduser -G app -u 1000 app -D

WORKDIR /home/app

COPY --chown=app:app --from=build /main .

USER app:app

EXPOSE 8080

CMD ["./main"]
